import { NFT_COLLECTION_ADDRESS } from '../../addresses';

export default [
  {
    name: 'Idaho',
    address: NFT_COLLECTION_ADDRESS,
    id: 1000005,
    category: 'Beer',
    imageUrl: '/images/collections/op-sepolia-test/wylie_idaho.png',
    meta: {},
  },
  {
    name: 'Cashmere',
    address: NFT_COLLECTION_ADDRESS,
    id: 1000006,
    category: 'Beer',
    imageUrl: '/images/collections/op-sepolia-test/wylie_cashmere.png',
    meta: {},
  },
  {
    name: 'Afterglow',
    address: NFT_COLLECTION_ADDRESS,
    id: 1000007,
    category: 'Beer',
    imageUrl: '/images/collections/op-sepolia-test/wylie_afterglow.png',
    meta: {},
  },
  {
    name: 'La Belle de Roquetes',
    address: NFT_COLLECTION_ADDRESS,
    id: 11,
    category: 'Beer',
    imageUrl:
      '/images/collections/op-mainnet/wylie/WYLIE-La_Belle_de_Roquetes.png',
    meta: {},
    limit: 200,
  },
  {
    name: 'Atlantis',
    address: NFT_COLLECTION_ADDRESS,
    id: 13,
    category: 'Beer',
    imageUrl: '/images/collections/op-mainnet/wylie/WYLIE-Atlantis.png',
    meta: {},
    limit: 200,
  },
  {
    name: 'Enter the Dragon',
    address: NFT_COLLECTION_ADDRESS,
    id: 14,
    category: 'Beer',
    imageUrl: '/images/collections/op-mainnet/wylie/WYLIE-Enter_the_Dragon.png',
    meta: {},
    limit: 200,
  },
  {
    name: 'Peace Yeast Love',
    address: NFT_COLLECTION_ADDRESS,
    id: 15,
    category: 'Beer',
    imageUrl:
      '/images/collections/op-mainnet/wylie/WYLIE-Peace_Yeast__Love.png',
    meta: {},
    limit: 200,
  },
  {
    name: 'Rain Dance',
    address: NFT_COLLECTION_ADDRESS,
    id: 16,
    category: 'Beer',
    imageUrl: '/images/collections/op-mainnet/wylie/WYLIE-Rain_Dance.png',
    meta: {},
    limit: 200,
  },
];
