import { ICollection } from '@/types';
import { NFT_COLLECTION_ADDRESS } from '../addresses';

export default {
  id: 1,
  name: 'prelaunch',
  address: NFT_COLLECTION_ADDRESS,
  network: 'op-sepolia-testnet',
  chainId: 11155420,
  color: 'rgba(99, 192, 172, 1)',
  cards: [
    {
      name: 'Boo',
      address: NFT_COLLECTION_ADDRESS,
      id: 0,
      category: 'Brewery',
      imageUrl: '/images/collections/op-sepolia-test/boo.gif',
      meta: {},
    },
    {
      name: 'The Beer Place',
      address: NFT_COLLECTION_ADDRESS,
      id: 1,
      category: 'Brewery',
      imageUrl: '/images/collections/op-sepolia-test/the-beer-place.gif',
      meta: {},
    },
    {
      name: 'Wow',
      address: NFT_COLLECTION_ADDRESS,
      id: 2,
      category: 'Brewery',
      imageUrl: '/images/collections/op-sepolia-test/wow.gif',
      meta: {},
    },
    {
      name: 'Free Beer',
      address: NFT_COLLECTION_ADDRESS,
      id: 3,
      category: 'Brewery',
      imageUrl: '/images/collections/op-sepolia-test/free-beer.gif',
      meta: {},
    },
    {
      name: 'Festival #1',
      address: NFT_COLLECTION_ADDRESS,
      id: 4,
      category: 'Festival',
      imageUrl: '/images/collections/op-sepolia-test/festival_1.png',
      meta: {},
    },
    {
      name: 'Wylie Brewery Idaho',
      address: NFT_COLLECTION_ADDRESS,
      id: 5,
      category: 'Brewery',
      imageUrl: '/images/collections/op-sepolia-test/wylie_idaho.png',
      meta: {},
    },
    {
      name: 'Wylie Brewery Cashmere',
      address: NFT_COLLECTION_ADDRESS,
      id: 6,
      category: 'Brewery',
      imageUrl: '/images/collections/op-sepolia-test/wylie_cashmere.png',
      meta: {},
    },
    {
      name: 'Wylie Brewery Afterglow',
      address: NFT_COLLECTION_ADDRESS,
      id: 7,
      category: 'Brewery',
      imageUrl: '/images/collections/op-sepolia-test/wylie_afterglow.png',
      meta: {},
    },
  ],
} as ICollection;
